### ISSUE TITLE
How to add and manage scripts

### ISSUE THREAD

**Issue by RashiqAzhan** [ryan4yin/nixos-and-flakes-book#130]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when letters BEcome like this as I type caps using the caps lock instead of shift. MAybe if something existed like a script that would fix this issue...

**Describe the solution you'd like**
IN my search, I've found [this](https://github.com/hexvalid/Linux-CapsLock-Delay-Fixer) but I do not know how to properly include a script using that runs after every login using NIx flakes or the config file. I would like an entry in the website that discusses the approaches to achieve this, pros and cons, and best practices.

**Describe alternatives you've considered**
I wish someone would fix this for real instead of having to resort to this. This is why linux will never takeover take the throne, *pls don't shoot me*.

**Additional context**
LOve your work. YOU've made my journey to NixOS finally bearable after all these years.

**Comment by ryan4yin** [comment]
ArchLinux 's Wiki also mentioned this problem & its workaround: [Switching state immediately when Caps Lock is pressed - ArchLinux Wiki](https://wiki.archlinux.org/title/Xorg/Keyboard_configuration#Switching_state_immediately_when_Caps_Lock_is_pressed)

NixOS provides some options related to xkb: [xkb - NixOS Options](https://search.nixos.org/options?channel=23.11&show=services.xserver.xkb.options&from=0&size=50&sort=relevance&type=packages&query=xkb).

I've come up with some solutions, but it's relatively troublesome. 
I suggest you post the information I provide, together with your question, to [NixOS Discourse](https://discourse.nixos.org/) and [NixOS subreddit](https://www.reddit.com/r/NixOS/) for help. There are many active users there, and maybe someone has solved this problem.
