### ISSUE TITLE
Translation?

### ISSUE THREAD

**Issue by Thatoo** [ryan4yin/nixos-and-flakes-book#137]
Hello,
What do you think about adding automatic translation to make your book accessible to even more newcomers?
Even if the initial translation from AI might not be perfect it could be good enough to help newcomers and they might then offer to improve translation.
https://github.com/marketplace/actions/gpt-translate

**Comment by ryan4yin** [comment]
Even with tools like GPT, it's still troublesome to maintain languages that I don't understand myself. 

I would suggest that users use browser extensions to translate the website on the client side.
BTW, If you want to maintain, you can fork this repoi and automatically translate upstream changes into other languages through GitHub Action and other methods.

I can accept the addition of a multilingual site/repo link to README.md, and I will declare that it is not maintained by me.
