### ISSUE TITLE
Dead links to "Adding Custom Cache Servers"

### ISSUE THREAD

**Issue by oofdere** [ryan4yin/nixos-and-flakes-book#149]
NixOS with Flakes > [Adding Custom Cache Servers](https://nixos-and-flakes.thiscute.world/nixos-with-flakes/add-custom-cache-servers) is missing on the website. It's linked to from the sidebar and at the bottom of the [previous page](https://nixos-and-flakes.thiscute.world/nixos-with-flakes/nixos-flake-and-module-system).

**Comment by ryan4yin** [comment]
Fixed by #148
