### ISSUE TITLE
Failed to switch to flake in virtualbox envrionment

### ISSUE THREAD

**Issue by fabilong** [ryan4yin/nixos-and-flakes-book#164]
newbie here and would appreciate it if anybody could explain this to me

error is
> cannot lookup '<nixpkgs/nixos/modules/installer/virtualbox-demo.nix>' in pure evaluation mode ( use '--impure' to override)

**Comment by ryan4yin** [comment]
`<xxx>` is a nix lookup path, as [Lookup paths - nix.dev](https://nix.dev/tutorials/nix-language#lookup-paths) said:

> While you will encounter many such examples, we recommend to [avoid lookup paths](https://nix.dev/guides/best-practices#search-path) in production code, as they are [impurities](https://nix.dev/tutorials/nix-language#impurities) which are not reproducible.

That's to say, lookup paths are impurities, and flake are pure by default, so flake will not accept it.

As the error suggest, you can add `--impure` at the end of your nix command to avoid this error.

A better solution is to switch to  `modulePaths` - A parameter available only in NixOS, which is a path pointing to [nixpkgs/nixos/modules](https://github.com/NixOS/nixpkgs/tree/nixos-23.11/nixos/modules).
An example: [hardware-configuration.nix](https://github.com/ryan4yin/nix-config/blob/i3-kickstarter/hosts/nixos-test/hardware-configuration.nix#L8)
