### ISSUE TITLE
提议更换网站的图标

### ISSUE THREAD

**Issue by Elecleus** [ryan4yin/nixos-and-flakes-book#192]
现在的图标和其他的 Nix Related 网站不能很好的区分，浏览器多页面查资料时只能通过标题分别。

**Comment by ryan4yin** [comment]
主要没找到什么合适的，所以我直接 copy 了官方图标，你有啥想法没。

**Comment by Elecleus** [comment]
既然项目名是 Nixos & Flakes Book，可以找一个 svg 格式的开源书籍图标，之后把雪花放在书上合适位置。

**Comment by ryan4yin** [comment]
要不就直接拿 banner 裁剪一下吧

**Comment by ryan4yin** [comment]
感觉 banner 当 icon 效果也不错，就这么着了，辨识度够高的（
