### ISSUE TITLE
Description of self in book is inaccurate

### ISSUE THREAD

**Issue by mwoodpatrick** [ryan4yin/nixos-and-flakes-book#207]
**Describe the bug**
In section 3 of the bool "The Special Parameter self of the outputs Function" the description of self in is inaccurate. Currently says:

`The special input named self refers to the outputs and source tree of this flake`

But actuality it refers to the whole flake.

**To Reproduce**
In a directory containing a flake (with a description, inputs & outputs) run the nix repl and do:

```
x=import ./flake.nix
x
```

This will generate something like

```
{
  description = "A simple NixOS flake";
  inputs = { ... };
  outputs = «lambda outputs @ /home/mwoodpatrick/config/nix/flake.nix:22:13»;
}
```
You can for example access the inputs (using x.inputs) e.g.:

```
nix-repl> x.inputs
{
  NixOS-WSL = { ... };
  nixpkgs = { ... };
  nixpkgs-stable = { ... };
}
```

**Comment by mwoodpatrick** [comment]
This does not prove my point, investigating

**Comment by ryan4yin** [comment]
> The special input named self refers to the outputs and source tree of this flake

I have provided the source links for this description in the book:

1. The Nix Manual: https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake#flake-inputs
2. The Source file of the Nix Manual: https://github.com/NixOS/nix/blob/2.25.3/src/nix/flake.md?plain=1#L478-L482

If you believe this information is inaccurate, I would encourage you to submit an issue to the Nix project for further clarification.

IMHO, the `flake.nix` is not just a simple Nix file; it’s a special one, so it would not work the same as `import flake.nix`.
