### ISSUE TITLE
# set this variable make i3 failed to start     XAUTHORITY = "$XDG_RUNTIME_DIR/Xauthority";

### ISSUE THREAD

**Issue by f0rdprefect** [ryan4yin/nixos-and-flakes-book#30]
Hi Ryan, 

totally awesome guide. When following your excellent guide I used the version 0.0.2 of your nix-config. Of course adjusting to my needs. It took me quite a while to figure out that i3 and also plasma would not start with the XAUTHORITY setting above. Maybe you could put a note about it in the guide? I hesitated to try the newer versions, because 0.0.2 is really a good balance to have modules set up and not too much complexity to grasp it.

Thanks again for bringing some order into the flakes world!

**Comment by ryan4yin** [comment]
Thanks for the feedback, your problem made me realize that the previous version of the setup was a bit sloppy.
If I had used v0.2.0 at the time, then I could have release a `v0.2.1` by now to fix the problem.
I'll take the time to see how to make it better.
