### ISSUE TITLE
Managing System Packages Problem: `error: flake input attribute 'helix' is a thunk while a string, Boolean, or integer is expected`

### ISSUE THREAD

**Issue by mikelane** [ryan4yin/nixos-and-flakes-book#41]
I've followed the directions [here](https://nixos-and-flakes.thiscute.world/nixos-with-flakes/nixos-with-flakes-enabled), but I'm getting the following error:

```shell
❯ sudo nixos-rebuild switch    
error:
       … while evaluating flake attribute 'helix'

         at /nix/store/fdhl5n49pbjlvmr8pqmgai03cpbsmj03-source/flake.nix:26:7:

           25|       # Helix editor, using version 23.05
           26|       helix.url = "github:helix-editor/helix/23.05";
             |       ^
           27|     };

       error: flake input attribute 'helix' is a thunk while a string, Boolean, or integer is expected
❯ 
```
Any idea how to fix this?

**Comment by mikelane** [comment]
Oof, nevermind. I had put that into the `inputs.home-manager` instead of into the `inputs` in the flake.nix.

**Comment by mikelane** [comment]
note: I did have to run `sudo nixos-rebuild switch --flake /etc/nixos#nixos-test` instead of just `sudo nixos-rebuild switch` to get helix to build. The docs leaves off the `--flakes ...` part.

**Comment by ryan4yin** [comment]
> note: I did have to run `sudo nixos-rebuild switch --flake /etc/nixos#nixos-test` instead of just `sudo nixos-rebuild switch` to get helix to build. The docs leaves off the `--flakes ...` part.

Added a description of this problem: https://github.com/ryan4yin/nixos-and-flakes-book/commit/baed45353c72ba3aa429391cb014682c7dea592e
