### ISSUE TITLE
Add additional explanation in "Managing the Configuration with Git" section

### ISSUE THREAD

**Issue by nykma** [ryan4yin/nixos-and-flakes-book#47]
Thank you for this awesome guide. IMHO there is one more very important piece of information that needs to be added to this section:

After you `git init` the configuration folder, you have to `git add` all the files into the `staged` status before you do the `nixos-rebuild switch`, otherwise you will see a very unclear error message.

Thank you.

**Comment by ryan4yin** [comment]
Updated, thanks for the feedback!
