### ISSUE TITLE
Add Serokell's blog to the "Intro to Flakes" chapter

### ISSUE THREAD

**Issue by evccyr** [ryan4yin/nixos-and-flakes-book#48]
After reading the "intro to flakes" as well as "nixos with flakes enabled" chapter, I was still unsure of how flakes worked. I found the Serokell's blog to be more helpful. If possible it'd be nice to link it or better than that copying their content non-verbatim to the book would be nice too.
https://serokell.io/blog/practical-nix-flakes

**Comment by ryan4yin** [comment]
Thank you for the suggestion, added: https://github.com/ryan4yin/nixos-and-flakes-book/commit/489a6a29b396eaf4a93235af9684dd4cc1d2ec29
