### ISSUE TITLE
Command slightly wrong

### ISSUE THREAD

**Issue by Biepa** [ryan4yin/nixos-and-flakes-book#51]
On https://nixos-and-flakes.thiscute.world/nixos-with-flakes/start-using-home-manager

There is the part:
"Then run sudo nixos-rebuild switch to apply the configuration, and home-manager will be installed automatically."

I went trough it twice and it did not work for me, but "sudo nixos-rebuild switch --flake /etc/nixos#nixos-test" did.

Obviously I'm a beginner with NixOs, so let me know if I missed anything.

**Comment by nykma** [comment]
Same for me. I found the ["standalone install guide" on HomeManager's doc](https://nix-community.github.io/home-manager/index.html#sec-install-standalone)

```sh
nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
nix-channel --update
nix-shell '<home-manager>' -A install
```

to get my `home-manager` executable usable. 

Seems like this way is not that flake-y, still waiting for a more flake-y solution.

**Comment by ryan4yin** [comment]
Fixed by https://github.com/ryan4yin/nixos-and-flakes-book/commit/4f60d3ccc816df6144647b2f2cbc8397c0fe6158

**Comment by ryan4yin** [comment]
> to get my `home-manager` executable usable. -- @nykma 

The `home-manager` executable is not necessary, `nixos-rebuild` is all you need.
