### ISSUE TITLE
helix flake problems ... tree-sitter ... returned  error 403

### ISSUE THREAD

**Issue by triklsbg** [ryan4yin/nixos-and-flakes-book#64]
`
sudo nixos-rebuild switch --flake .#nixos-test

Schwerwiegend: konnte nicht auf https://git.sr.ht/~sfr/tree-sitter-gemini/ zugreifen: The requested URL returned error: 403
error:
       … while calling the 'head' builtin

         at /nix/store/4fgs7yzsy2dqnjw8j42qlp9i1vgarzy0-source/lib/attrsets.nix:936:11:

          935|         || pred here (elemAt values 1) (head values) then
          936|           head values
             |           ^
          937|         else

       … while evaluating the attribute 'value'

         at /nix/store/4fgs7yzsy2dqnjw8j42qlp9i1vgarzy0-source/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: program 'git' failed with exit code 128

`

**Comment by ryan4yin** [comment]
Related to https://github.com/helix-editor/helix/issues/8933, switching to the master branch of helix can solve this problem, or wait for the next version of helix to be released.

**Comment by ryan4yin** [comment]
Fix by https://github.com/ryan4yin/nixos-and-flakes-book/commit/40b5fc05ee576b73fca0ba09c2f2f759fe22cd61
