### ISSUE TITLE
nix-daemon设置网络代理环境变量无法生效问题

### ISSUE THREAD

**Issue by kmjuq** [ryan4yin/nixos-and-flakes-book#74]
## 环境
设备：macbook 
虚拟机：vmware
nixos版本：23.11
## 问题
![image](https://github.com/ryan4yin/nixos-and-flakes-book/assets/22958563/3d0bc348-90ce-487e-82cf-1f7ea0752199)

我根据你的博客的内容设置了代理，但是还是无法生效，我弄了一个shell脚本来进行这个配置。
\# export https_proxy=http://192.168.31.172:7890/ http_proxy=http://192.168.31.172:7890/ all_proxy=socks5://192.168.31.172:7890
\# export https_proxy=http://127.0.0.1:7890/ http_proxy=http://127.0.0.1:7890/ all_proxy=socks5://127.0.0.1:7890
sudo mkdir /run/systemd/system/nix-daemon.service.d/
cat << EOF >/run/systemd/system/nix-daemon.service.d/override.conf
[Service]
Environment="http_proxy=http://192.168.31.172:7890/"
Environment="https_proxy=http://192.168.31.172:7890/"
Environment="all_proxy=socks5://192.168.31.172:7890"
EOF
sudo systemctl daemon-reload
sudo systemctl restart nix-daemon

**Comment by ryan4yin** [comment]
两个排查方向：

1. 给 `nixos-rebuild switch` 添加 `--show-trace -L` 参数获取更详细的错误日志，看看能否定位到问题。
2. 通过 `ps eww | grep nix-daemon` 查看 nix-daemon 进程的所有环境变量，确认环境变量的设置是否生效。

**Comment by ryan4yin** [comment]
已补充相关提示：https://github.com/ryan4yin/nixos-and-flakes-book/commit/1df6c6ff7a253c869700978206d26a20c9a845e1
