### ISSUE TITLE
 is possale to add a discussions（chat） in book ?

### ISSUE THREAD

**Issue by xBLACKICEx** [ryan4yin/nixos-and-flakes-book#94]
## Is possale to add a discussions（chat） in book ?

This will allow for some questions to be asked, if every time some small problem or question is encountered during the reading, it is not appropriate to go to other chat software or issue.

#### For example, for this [hello-alogo](https://github.com/krahets/hello-algo) project, the chats and **_github discussions_**  are linked together:
https://www.hello-algo.com/chapter_computational_complexity/#_1
![Screenshot_20240226_215536](https://github.com/ryan4yin/nixos-and-flakes-book/assets/51036094/8661411e-10a4-4a18-ae43-b0a8da89788d)

https://github.com/krahets/hello-algo/discussions/532#discussioncomment-7728060
![Screenshot_20240226_215902](https://github.com/ryan4yin/nixos-and-flakes-book/assets/51036094/30ebf6c9-bfcd-487c-822d-b800ab764213)

**Comment by ryan4yin** [comment]
Love the idea! Giscus has been added for this purpose: #96
